In [1]:
pip install numpy


In [2]:
import numpy as np


In [3]:
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [17]:
arr1=np.array([1,2,3])
arr2=np.array([[1,2,3],[5,8,0]])
arr3=np.array([[[1,2,3],[5,8,0]],[[4,6,4],[5,3,1]]])
print(arr1)
print(arr2)
print(arr3)

[1 2 3]
[[1 2 3]
 [5 8 0]]
[[[1 2 3]
  [5 8 0]]

 [[4 6 4]
  [5 3 1]]]


In [18]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [21]:
zeros=np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
ones=np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
random=np.random.random((3,2))
print(random)

[[0.90195525 0.41965079]
 [0.81614906 0.85243261]
 [0.61584549 0.99496618]]


In [31]:
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
arr_range=np.arange(0,10,2)
print(arr_range)

[0 2 4 6 8]


In [37]:
arr=np.array([[1,2,3],[5,2,9]])
print("Shape:",arr.shape)
print("size:",arr.size)
print("data type:",arr.dtype)
print("number of dimension:",arr.ndim)

Shape: (2, 3)
size: 6
data type: int64
number of dimension: 2


You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.
Each greenhouse has sensors that record temperature (°C) readings at different times of the day.
You received the following data:
Your tasks are:
Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity.

In [45]:
temp_data = np.array([[22,25,20],[24,26,23]])
print(temp_data)
print("Shape:",temp_data.shape)
print("size:",temp_data.size)
print("data type:",temp_data.dtype)
print("number of dimension:",temp_data.ndim)


[[22 25 20]
 [24 26 23]]
Shape: (2, 3)
size: 6
data type: int64
number of dimension: 2


Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.

In [52]:
gh3=[21,23,22]
updated_temp_data=np.append(temp_data,[gh3],axis=0)
print(updated_temp_data)

[[22 25 20]
 [24 26 23]
 [21 23 22]]


In [54]:
sensor_error_flags=np.zeros((2,3))
greenhouse_identity=np.ones((3,3))
print(sensor_error_flags)
print(greenhouse_identity)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [55]:
print(updated_temp_data)
print(sensor_error_flags)
print(greenhouse_identity)

[[22 25 20]
 [24 26 23]
 [21 23 22]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [60]:
#index slicing
arr1=np.array([1,2,3,4,5,6,7])
print(arr1[1:5])
arr2=np.array([[1,2,3],[4,5,2]])
print(arr2[1,2])
print(arr2[1,-2])

[2 3 4 5]
2
5


In [67]:
arr1=np.array([1,2,3,4,5,6,7])
print(arr1[1::2])
arr2=np.array([[1,2,3],[4,5,2]])
print(arr2[:,1:])

[2 4 6]
[[2 3]
 [5 2]]


In [68]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print(shipments)

[[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]


In [70]:
print("no.of apples shipped on wed:",shipments[0,2])
print("no.of oranges shipped on sun:",shipments[1,6])

no.of apples shipped on wed: 55
no.of oranges shipped on sun: 75


In [74]:
# Access multiple elements (Slicing):
# Extract all the weekday shipments (Mon–Fri) for all fruits.
# Extract only the weekend shipments (Sat & Sun).
# Extract the shipments of Apples from Wednesday to Saturday.
print("all the weekday shipments (Mon–Fri) for all fruits:",shipments[:,:5])
print("Extract only the weekend shipments (Sat & Sun):",shipments[:,5:])
print("Extract the shipments of Apples from Wednesday to Saturday:",shipments[0,2:6])


all the weekday shipments (Mon–Fri) for all fruits: [[50 60 55 70 65]
 [40 45 50 60 55]]
Extract only the weekend shipments (Sat & Sun): [[80 90]
 [70 75]]
Extract the shipments of Apples from Wednesday to Saturday: [55 70 65 80]


In [79]:
# Bonus (Practice thinking):
# Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.
shipments[0,5]=100
print(shipments)

[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [82]:
a=np.array([2,3,5])
b=np.array([6,3,2])
print(a+b)
print(a*b)
print(a*2)

[8 6 7]
[12  9 10]
[ 4  6 10]


In [86]:
a=np.array([[2,3,5],[3,1,2]])
b=np.array([[6,3,2],[5,7,1]])
print(a*b)
print(a*2)

[[12  9 10]
 [15  7  2]]
[[ 4  6 10]
 [ 6  2  4]]


In [87]:
a=np.array([2,3,5])
b=np.array([6,3,2])
res=np.dot(a,b)
print(res)

31


In [89]:
a=np.array([2,1,3])
b=3
print(a+b)

[5 4 6]


In [107]:
a=np.array([2,4,6])
print(np.exp(a))
print(np.sqrt(a))
print(np.log(a))
print(np.max(a))
print(np.min(a))
b=[3.43,2.1,1.45]
print(np.round(b))
print(np.floor(b))
print(np.ceil(b))
print(np.trunc(b))
print(np.sum(b))



[  7.3890561   54.59815003 403.42879349]
[1.41421356 2.         2.44948974]
[0.69314718 1.38629436 1.79175947]
6
2
[3. 2. 1.]
[3. 2. 1.]
[4. 3. 2.]
[3. 2. 1.]
6.98


In [111]:
farm_a=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farm_b=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farm_c=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
print(farm_a)
print(farm_b)
print(farm_c)


[[10 12 11]
 [ 9 11 10]
 [12 13 14]
 [ 8  7  9]]
[[20 19 21]
 [18 20 19]
 [22 23 21]
 [17 18 16]]
[[15 16 14]
 [14 13 15]
 [16 17 18]
 [12 11 13]]


In [115]:
production_all=np.stack([farm_a,farm_b,farm_c],axis=0)
print(production_all)

[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]


In [116]:
print("Shape:",production_all.shape)
print("size:",production_all.size)
print("data type:",production_all.dtype)
print("number of dimension:",production_all.ndim)

Shape: (3, 4, 3)
size: 36
data type: int64
number of dimension: 3


In [119]:
total_per_farm=production_all.sum(axis=(1,2))
print(total_per_farm)

[126 234 174]


Compute mean, std, and var per farm.

In [120]:
mean_per_farm=production_all.mean(axis=(1,2))
std_per_farm=production_all.std(axis=(1,2))
var_per_farm=production_all.var(axis=(1,2))
print(mean_per_farm)
print(std_per_farm)
print(var_per_farm)

[10.5 19.5 14.5]
[1.97905701 1.97905701 1.97905701]
[3.91666667 3.91666667 3.91666667]


Per-hour matrix multiplication idea (matrix op)

In [121]:
hour_weights=np.array([0.5, 1.0, 0.75])
weighted_per_panel = np.dot(production_all, hour_weights)
print(weighted_per_panel)

[[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]


Broadcasting adjustments

In [126]:
offset=0.5
production_all = production_all.astype(float)
production_all[1] += offset
print(production_all)

[[[10. 12. 11.]
  [ 9. 11. 10.]
  [12. 13. 14.]
  [ 8.  7.  9.]]

 [[22. 21. 23.]
  [20. 22. 21.]
  [24. 25. 23.]
  [19. 20. 18.]]

 [[15. 16. 14.]
  [14. 13. 15.]
  [16. 17. 18.]
  [12. 11. 13.]]]


Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.

In [129]:
mean_per_farm = production_all.mean(axis=(1,2))
std_per_farm = production_all.std(axis=(1,2))
print(mean_per_farm)
print(std_per_farm)

[10.5 21.5 14.5]
[1.97905701 1.97905701 1.97905701]


In [130]:
mean_per_farm = mean_per_farm[:, np.newaxis, np.newaxis]  # shape (3,1,1)
std_per_farm = std_per_farm[:, np.newaxis, np.newaxis]    # shape (3,1,1)
print(mean_per_farm)
print(std_per_farm)

[[[10.5]]

 [[21.5]]

 [[14.5]]]
[[[1.97905701]]

 [[1.97905701]]

 [[1.97905701]]]


In [131]:
normalized_production = (production_all - mean_per_farm) / std_per_farm
print(normalized_production)

[[[-0.25264558  0.75793673  0.25264558]
  [-0.75793673  0.25264558 -0.25264558]
  [ 0.75793673  1.26322788  1.76851903]
  [-1.26322788 -1.76851903 -0.75793673]]

 [[ 0.25264558 -0.25264558  0.75793673]
  [-0.75793673  0.25264558 -0.25264558]
  [ 1.26322788  1.76851903  0.75793673]
  [-1.26322788 -0.75793673 -1.76851903]]

 [[ 0.25264558  0.75793673 -0.25264558]
  [-0.25264558 -0.75793673  0.25264558]
  [ 0.75793673  1.26322788  1.76851903]
  [-1.26322788 -1.76851903 -0.75793673]]]


7.8.9,,,
Apply many ufuncs (use the ufuncs listed previously)
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.

In [133]:
arr=np.array([3,4,5,6,8,3])
reshape=arr.reshape(2,3)
print(reshape)

[[3 4 5]
 [6 8 3]]
[[3 4 5]
 [6 8 3]]


stacking and splitting


In [140]:
a=np.array([1,2])
b=np.array([3,4])
#vertical stack
print(np.vstack((a,b)))
#horizontal stack
print(np.hstack((a,b)))

arr=np.array([1,2,4,6,7,8])
print(np.split(arr,3))
print(np.split(arr,[2,4]))

[[1 2]
 [3 4]]
[1 2 3 4]
[array([1, 2]), array([4, 6]), array([7, 8])]
[array([1, 2]), array([4, 6]), array([7, 8])]


In [141]:
arr=np.array([1,2,4,6,7,8])
print(arr[arr>3])

[4 6 7 8]


In [143]:
arr=np.array([1,2,4,6,7,8])
indeces=[0,4]
print(arr[indeces])

[1 7]


copy nd view


In [146]:
arr=np.array([1,2,3])
view=arr.view()
view[1]=10
print(arr)

[ 1 10  3]


In [152]:
copy=arr.copy()
copy[0]=10
print(copy)

[10  2  3]


saving and loading

In [153]:
arr=np.array([1,2,3])
np.save("array.npy",arr)

In [154]:
loaded_arr=np.load("array.npy")
print(loaded_arr)

[1 2 3]


Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.

In [156]:
arr=np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [158]:
arr1=np.random.random((3,3))
print(arr1)

[[0.25296113 0.40691166 0.59517525]
 [0.67453533 0.89768466 0.86112   ]
 [0.45867502 0.32131229 0.47627182]]


In [160]:
# Find the shape, size, and data type of the array you created in the previous task.
print("Shape:",arr.shape)
print("size:",arr.size)
print("data type:",arr.dtype)


Shape: (41,)
size: 41
data type: int64


In [161]:
arr += 5
print(arr)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [162]:
a=np.array([[1,2],[4,2]])
b=np.array([[2,3],[7,4]])
print(a*b)

[[ 2  6]
 [28  8]]


Indexing and Slicing:
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.

In [165]:
arr = np.arange(1, 26).reshape((5, 5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [166]:
# firstrow
print(arr[:1])

[[1 2 3 4 5]]


In [167]:
# last coloumn
print(arr[:,-1:])

[[ 5]
 [10]
 [15]
 [20]
 [25]]


In [171]:
# subarray of the first three rows and first two columns
print(arr[:3, :2])

[[ 1  2]
 [ 6  7]
 [11 12]]


Aggregation:
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.

In [179]:
arr=np.random.randint(10,100,10)
print(arr)
print("max:",max(arr))
print("min:",min(arr))
print("mean:",arr.mean(axis=0))
print("std:",arr.std(axis=0))

[91 72 22 33 44 58 68 73 45 32]
max: 91
min: 22
mean: 53.8
std: 20.96568625158738


Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.

In [185]:
arr=np.arange(1,13)
print(arr)

mat=arr.reshape(3,4)
print(mat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Broadcasting:
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.

In [189]:
arr=np.ones((3,3))
print(arr)

ar1d=[1,2,3]
print(arr+ar1d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


Filtering:
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.

In [195]:
arr = np.random.randint(1, 51, size=10)
print(arr)
div_by_5 = arr[arr % 5 == 0]
print("Divisible by 5:", div_by_5)

[45  2 22 48 12 18 24  8  5 14]
Divisible by 5: [45  5]


In [196]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
C = np.dot(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A x B:\n", C)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A x B:
 [[19 22]
 [43 50]]


Advanced Indexing:
Given a 4x4 array, use fancy indexing to extract the diagonal elements.


In [197]:

arr = np.arange(1, 17).reshape(4, 4)
print("Array:\n", arr)

diag = arr[np.arange(4), np.arange(4)]
print("Diagonal elements:", diag)


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagonal elements: [ 1  6 11 16]
